---
title: "Visualizations_analysis"
format: html
editor: visual
---

## 

### Libraries

```{r}
library(tidyverse)
library(readr)
library(knitr)
library(scales)
library(here)
```

### Data import

```{r}
match_df <- read_csv(here("data", "proccesed", "perfect_matches_2_0.csv"))
protein_meta <- read_csv(here("data", "intermediate", "protein_metadata.csv"))

iedb_df <- read_csv(here("data", "intermediate", "wrangled_IEDB.csv"))
```

### Pathogen data inspection

```{r}

# Top 15 species by number of proteomes
protein_meta |>
  group_by(Genus_Species) |>
  summarise(n = n_distinct(Proteome_ID)) |>
  arrange(desc(n)) |>
  slice_head(n = 15) |>
  ggplot(aes(x = reorder(Genus_Species, n), y = n)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Number of Proteomes per Pathogen Species",
    x = "Pathogen organism",
    y = "Number of proteomes"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

protein_meta |>
  group_by(Genus_Species) |>
  summarise(n = n_distinct(Proteome_ID)) |>
  ggplot(aes(x = n)) +
  geom_histogram(bins = 40, fill = "steelblue", color = "black") +
  labs(
    title = "Distribution of Proteomes per Pathogen Species",
    x = "Number of proteomes per species",
    y = "Number of species"
  ) +
  theme_minimal()
```

### IEDB data inspection

```{r}
# Top 15 epitope source proteins by number of epitopes
iedb_df |>
  group_by(Protein_source) |>
  summarise(n = n()) |>
  arrange(desc(n)) |>
  slice_head(n = 15) |>
  ggplot(aes(x = reorder(Protein_source, n), y = n)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Number of Epitopes per Source Protein",
    x = "Epitope source protein",
    y = "Number of epitopes"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

# Histogram of epitope counts per source protein
iedb_df |>
  count(Protein_source, name = "n") |>
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50, fill = "steelblue", color = "black") +
  labs(
    title = "Distribution of Epitopes per Source Protein",
    x = "Number of epitopes per source protein",
    y = "Number of source proteins"
  ) +
  theme_minimal()
```

### matches inspection (IEDB data)

```{r}
# Top 15 epitope source proteins by number of epitopes
match_df |>
  group_by(IEDB_Protein_ID) |>
  summarise(n = n()) |>
  arrange(desc(n)) |>
  slice_head(n = 15) |>
  ggplot(aes(x = reorder(IEDB_Protein_ID, n), y = n)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Number of matches per IEDB protein",
    x = "Epitope source protein",
    y = "Number of Matches"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

# Histogram of epitope counts per source protein
match_df |>
  count(IEDB_Protein_ID, name = "n") |>
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50, fill = "steelblue", color = "black") +
  labs(
    title = "Distribution of matches per IEDB protein",
    x = "Number of matches per source protein",
    y = "Number of unique source proteins"
  ) +
  theme_minimal()
```
